# Generated by Django 4.1.5 on 2023-01-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(max_length=50)),
                ('website_link', models.URLField(null=True)),
                ('website_username', models.CharField(max_length=50)),
                ('website_password', models.CharField(max_length=50)),
                ('website_notes', models.CharField(max_length=50, null=True)),
                ('master_password', models.CharField(default='', max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
